### PR TITLE
Additional supplements changes that missed a previous merge

### PR DESCRIPTION
**Pull request by TheTechmage**
When working with Chris and Ammon, it was discovered that we were missing these changes from the credentials-attachments branch and it was causing errors for them.

### CODE REVIEW

**Comment by TheTechmage** [comment]
Hey @reflectivedevelopment? What is needed to get a new image over to Chris and Ammon?

**Review by dbluhm — APPROVED** [review]
Tested and passing

**Comment by swcurran** [comment]
Are you planning to push this to ACA-Py?  It's going to create some fun, as @shaanjotgill25 is already working on V2.1 of issue credential.   I'm assuming this work does not include v2.1 support -- just v2.2?

All good -- we can work it out...

In your work, have you included support for a credential supplement shared with the Credential Offer?

**Comment by swcurran** [comment]
FYI @shaangill025 ^^^

**Comment by dbluhm** [comment]
@swcurran this specific branch (and the one being merged into it) is something we're using internally. The branch with our changes is found at feature/credential-attachments. We would definitely like to be able to get this merged upstream. It only contains changes for v2.2 and the implementation for JSON-LD creds is currently stubbed out (i.e. hashlink supplements are only implemented for AnonCreds).

**Comment by TheTechmage** [comment]
Yep! As Daniel said, this PR is specifically something we're using internally. It's a backport of the `feature/credential-attachments` branch to 0.7.4. The `feature/credential-attachments` was based off of main (if I remember correctly) making it more easily mergeable upstream. I don't believe that work is ready to merge in *yet*, and a PR should be created once we believe the feature is ready.

**Comment by swcurran** [comment]
Sounds good.  We can discuss how to get both versions together.  I think we probably should let Shaanjot complete v2.1 and merged into ACA-Py, and then apply these changes on top of that -- likely via manually moving the code over, but we'll see.

**Pull request merged**
